events {}
http {
    upstream my_app {
        # On liste nos deux réplicas de l appli
        server app_rembourse_1:80;
        server app_rembourse_2:80;
    }

    server {
        listen 80;
        location / {
            proxy_pass http://my_app; # Nginx envoie le trafic vers les réplicas
        }
    }
}